### ISSUE TITLE
VBUS protocol 2.0 parameters documentation

### ISSUE THREAD

**Issue by adliner** [danielwippermann/resol-vbus#22]
Hi,
is there any known source of the documentation for protocol 2.0 parameters?

I mean specifically a documentation which would allow to match specific menu functionalities to parameter index/address. 

And I'm specifically referring to DeltasolMX controller.

Thanks,
Adam

**Comment by danielwippermann** [comment]
Hi Adam,

sorry for not answering earlier...

Regarding your question: no, not that I know of. The parameter names can be a hint if you understand german and know the corresponding functionality in the controller. But I do not know of any public formal explanation on which value causes what.

That said: if you could provide me which a SET file of your current config, I could generate a list which values were changed to what. Something like the Settings Documentation Generator provided by VBus.net, but extended with the names and indices of the parameters involved.

Best regards,
Daniel

**Comment by adliner** [comment]
Hi Daniel,
few years ago I received some html documentation of Vbus protocol 2.0 parameters for DeltasolMX. As I'm not sure if it's been made public I wouldn't like to publish this without the consent of the company. Though I'm personally convinced that it should be made public anyway, it would allow for a deeper integration with RESOL products. The addresses/indices from the documentation used to work fine with DeltasolMX controllers with FW:1.06 on board but are no loner valid for FW:2.05. Using my really basic knowledge of german I was able to identify proper items (associate particular menu items with parameter names).

I'm not quite sure what you're referring to by saying 'SET file of your current config' but the few parameters I'm interested in are posted here:
https://github.com/adliner/resol_params_config/blob/master/params_config.txt 

These are valid for FW:1.06 and I'm looking for their corresponding addresses/indices for FW:2.05.

Thanks for response :),
Adam

**Comment by danielwippermann** [comment]
Hi Adam,

I think I known which HTML file you mean. There is currently no such file for the MX 2.x, but RESOL is working on it.

I'll get back to you once I have more news...

Best regards,
Daniel

**Comment by danielwippermann** [comment]
Hi Adam,

the documentation is ready. If you don't have it yet, just write me a mail to daniel.wippermann@gmail.com and I'll send you a link to it.

The parameters `Heizung_Heizkreis1_Heizkurve` and `Heizung_Heizkreis2_Heizkurve` still exist in the MX 2.x, but the `Heizung_Heizkreis1_Schaltuhr_Woche_TagXX_MaskeX` values are gone and replaced by other values. To know which values are used you have to read the `Heizung_Heizkreis1_SchaltuhrNr` value. You'll receive a value between 1 and 50 which then can be used to read the `Wsu{number just read}_...` values containing the actual timer information. So if you read a 4 from `Heizung_Heizkreis1_SchaltuhrNr` you will need to read the `Wsu4_...` values afterwards.

If you have any additional question don't hesitate to contact me. Otherwise I'll close this ticket in a couple of weeks.

Best regards,
Daniel

**Comment by danielwippermann** [comment]
I'm closing this issue for now. Feel free to open a new one if you have additional questions.
