### ISSUE TITLE
with iobroker.resol (daniel wippermann) v 0.22.0 the connection can't be established

### ISSUE THREAD

**Issue by SurfGargano** [danielwippermann/resol-vbus#58]
Daniel has changed the connection procedure in thje v0.22.0 , so an error is shown and no connection is established :  Unable to create optimizer for master with address 0x1121

**Comment by danielwippermann** [comment]
I do not have a CS2 controller, but the "customizer" example, that uses the error message you quote, works fine for my MX:

```
Connecting...
Connection state changed to CONNECTING
Connection state changed to CONNECTED
Waiting for free bus...
Found master with address 0x7e11
[1] Optimizing set of values for round 1
Waiting for free bus
Getting value 1/248, try 1: Language
...
```

Could you please provide more details about the error you are seeing? Which node version are you running on? Because that is the most obvious thing that changed in version 0.22.0: we dropped support for node versions lower than 12. If you are running iobroker on a node version below that things might break.

Thanks in advance,
Daniel

**Comment by SurfGargano** [comment]
NodeJS 12.22.1, more details tomorrow

**Comment by danielwippermann** [comment]
Thanks, your support is appreciated!

I ran my little test script again under node 12.22.1 and it worked there as well...

Until tomorrow!
Daniel

**Comment by SurfGargano** [comment]
I think I've got it. I have manually installed resol-vbus with npm in /opt/iobroker.
But there is a second installation in /opt/iobroker/node_modules/iobroker.resol/node_modules/resol-vbus/.
I suppose this installion is done with install iobroker.resol. With this installation there are missing the optimizer files for 0x1121.
