### ISSUE TITLE
credentials for http://{{resol_IP}}/cgi-bin/resol-webservice REST API

### ISSUE THREAD

**Issue by thampp** [danielwippermann/resol-vbus#76]
I have a new KM2 working. I can get to the local web application but I want to use the REST API as well.
The GET http://{{resol_IP}}/cgi-bin/get_resol_device_information works fine and returns:

> vendor = "RESOL"
> product = "KM2"
> serial = "40A36BCB595A"
> version = "2.0.0"
> build = "rc1"
> name = "KM2-40A36BCB595A"
> features = "vbus,wifi"

But for the calls to POST  http://{{resol_IP}}/cgi-bin/resol-webservice I need the "authId" parameter (I got that much from reading the other issues and internet posts).
To get an authId I try to call with  "method": "login" . But I don't know which username/password to provide in the body. I tried my vbus.net user/pw and that does not work (did not think it would - was expecting some local authentication). But the local webinterface has no named users and I can't leave the username empty either. So I keep getting this error.

Any tipps would be greatly appreciated. I do understand I could use the Javascript VBUS server from this Git repo - but for my purpose some simple REST calls are much easier to integrate (I want to use this with node red).

Thanks in advance for the help!

> [
>     {
>         "jsonrpc": "2.0",
>         "id": "1",
>         "error": {
>             "category": "App",
>             "message": "Invalid credentials"
>         }
>     }
> ]

**Comment by thampp** [comment]
BTW: I could get the http://192.168.1.199:3333/api/v1/live-data to work for me. It does return values that look legit.
I kept the default pw in my config.js. Since that seemed to work here I tried it the REST API as well with a few different user names. But no luck :-)

**Comment by thampp** [comment]
I have found the answer via another thread by now. The username to use is "admin".

**Comment by thampp** [comment]
@danielwippermann In what sense "new" - just newly/recently installed or is my KM2 some kind of new version?

I still have not been able to register it in vbus.net. Getting an "invalid token" error and send email to support.

But with the "admin user information I have been able to get it into my nodered->influxdb->grafana chain to render nice dashboards like this:
![image](https://user-images.githubusercontent.com/13353725/164736166-d5d5f788-c150-415b-bd0d-25610c9d5f66.png)

**Comment by thampp** [comment]
And two more questions if you have some time:
- I get an "Error mask" returned. Right now it's always 0. But I guess it would change to non-zero when problem occur. Is there some documentation on what the value semantics is? I guess it's some kind of bitmask. I suspect the example below from your live data server shows the bit semantics. Is that speculation correct?
- I also get an "Heat quantity" metric. It's always 0 as well. Is that just a limitation of my installation (no sensor connected or something)?

> resol{id="00_0010_1001_10_0100_036_4_0",name="Error mask"} 0
> resol{id="00_0010_1001_10_0100_036_1_1",name="Error: Sensor line broken"} 0
> resol{id="00_0010_1001_10_0100_036_1_2",name="Error: Sensor line short-circuited"} 0
> resol{id="00_0010_1001_10_0100_036_1_32",name="Error: Flow rate monitoring"} 0
> resol{id="00_0010_1001_10_0100_036_1_64",name="Error: Overpressure"} 0
> resol{id="00_0010_1001_10_0100_036_1_128",name="Error: Low pressure"} 0
> resol{id="00_0010_1001_10_0100_036_1_512",name="Error: Data memory"} 0
> resol{id="00_0010_1001_10_0100_036_1_1024",name="Error: Real-time clock"} 0
> resol{id="00_0010_1001_10_0100_036_1_4096",name="Error: Twin pump"} 0

**Comment by danielwippermann** [comment]
> In what sense "new" - just newly/recently installed or is my KM2 some kind of new version?

According to the dump above your device runs firmware version 2.0.0 which is relatively new and only runs on a recently released hardware revision. Older KM2s running firmware 1.x.x are incompatible to run 2.x.x.

> I still have not been able to register it in vbus.net. Getting an "invalid token" error and send email to support.

It should also show the token under "Configuration" / "Remote control" once you activate VBus.net there. Perhaps that token works?

Regardings the "error mask" question: yes, it is a bit field and - as you guessed - 0 means that no errors are currently reported. The structure of the bitmask differs from controller to controller. Can you tell me the packet field ID of your error mask (like the "00_0010_1001_10_0100_036_4_0" in my case above). I'll then try to find the meaning of the respective bits.

And regarding the "heat quantity": depending on your controller type there is an option in the user interface (sometimes called "OHQM" in the english translation for "option heat quantity measurement"). You need to activate that option, most certainly collect additional sensors and then configure a way to measure or estimate volume flow. Once again: when I know, what controller you have, I might be able to give better advise :)

**Comment by danielwippermann** [comment]
And by the way: the graphs look great, good job!

**Comment by thampp** [comment]
Hi Daniel - thanks for your answer - I really appreciate all the help!

> It should also show the token under "Configuration" / "Remote control" once you activate VBus.net there. Perhaps that token works?

This page shows the same token that is printed on the stickers and is also shown on the status page. I clicked the "Update Webportal Stage" button on that page several time (I assume one has to do that :-) ) But nothing changed: I still get the "Invalid Token" error in VBus.net and no reply to my email to support@resol.de yet.

> Can you tell me the packet field ID of your error mask (like the "00_0010_1001_10_0100_036_4_0" in my case above). 

I got this from http://127.0.0.1:3333/api/v1/live-data. I hope that is what you need
```
    {
        "id": "00_0010_4211_10_0100_010_1_0",
        "name": "Error mask",
        "rawValue": 0
    }
```
Looking forward to see what could be done regarding heat quantity measurement. We did have the problem in the past where air was in pipes and for a long time we did not notice. The pumps were still pumping, temperature coming down from the roof looked roughly reasonable. But there wasn't enough "volume" pumped through and one indication of the problem was that the panels went into overheated state far to quickly. At least that is what I suspect was the case at that time. Without proper measurement (and no KM2 yet :-) ) it was hard to tell.

**Comment by danielwippermann** [comment]
Ok, the packet field ID points to the SKSC family of controllers: http://danielwippermann.github.io/resol-vbus/#/vsf/fields/00_0010_4211_10_0100

I found an old manual that looked like it could belong to your type of controller and it states that the heat quantity measurement option is only available if the configured system is either 1, 3, 4 or 5. I believe it has something to do with sensor S4 which is unused only in those systems. In all other systems the OHQM option is not visible in the controller's user interface.

S4 is always used for the return temperature of the medium running from the tank back into the collector. Depending on the configured system either S1 or S3 is used for the flow temperature (collector -> tank). So you would basically have to mount one or two sensors and place them at the respective positions, enable the OHQM option and configure the values for FMAX, MEDT and MED%. The controller will then calculate the heat gain when the pump on relais 1 is running.

Since this HQM does not use a real flow metering device but instead only estimate the flow based on pump speed and a configured max flow value it might not suffienciently solve your problem. Because it would still accumulate heat gain even if there is air in the system and no fluid is transported at all.

Sadly it seems that the controller you have has no input for a flow metering device...

I also had a quick look at the error mask. It seems that only the lower four bits are used. Every bit represents one of the sensors and will go to "1" if the sensor has an error and is currently used for controlling purposes.

- Bit 0, Value 1: sensor 1 is in use, but reports a defect
- Bit 1, Value 2: sensor 2 is in use, but reports a defect
- Bit 2, Value 4: sensor 3 is in use, but reports a defect
- Bit 3, Value 8: sensor 4 is in use, but reports a defect

All other bits are unused.

**Comment by danielwippermann** [comment]
Regarding your KM2's token: please click on that "query portal ..." button once again. I restarted a VBus.net component which could - in theory - hand out an outdated token.

**Comment by danielwippermann** [comment]
And if that does not solve your problem feel free to generate a support report from the KM2's status page and send it to my work mail address (daniel.wippermann@resol.de). That could help sorting out the problem...

**Comment by thampp** [comment]
Super - jetzt hat es funktioniert.
Vielen Dank!!
![image](https://user-images.githubusercontent.com/13353725/164887138-41a35f59-557a-4dd5-8cb0-819e0b6357f3.png)
