### ISSUE TITLE
Setup adapter showing multiple subfolder; addtl. parameter from Controller DeltaMX available?

### ISSUE THREAD

**Issue by RESDE** [danielwippermann/resol-vbus#83]
Dear owner of the adapter,

1st of all: great that you spent your time so far to enable others to access resol devices for IOBroker integration.

After the installation (Base is the KM2 with an Resolte Delta MX Controller) the object tree shows various subfolders. Would you mind to share what is the differentation? Purpose of each subfolder.

![image](https://user-images.githubusercontent.com/59728312/203276190-fb09ab3e-66b3-477d-8c20-f0beade9d622.png)

Is renaming possible to have more than just the standard out of the initial setup based on the output of the controller? E.g. Sensor 1 = renamed in Sensor Roof-Kollektor?

Where and do I get access the more specific parameters of the delta Sol controller? E.g. the Delta Temperature between Sensor 1 and e.g. the linked buffersensor S2. Delta T is about 10 Greed where to start the solar pump. Would it be posible to read these parameters as well with the adapter per standard and convert it inot a nice subfolder. I have read all your hints to access deeper into the controller but Ißm not so familiar with JS etc. So a kind of Pro-Support from your side would be fantatstic.... Regasds Reiner

Installing adapter: done
accessing VBUS KM2 interface: done
how to use the objects in IOBroker (States): open

**Comment by danielwippermann** [comment]
Hi @RESDE !

I'll close this issue since the owner of the adapter did not respond here.

Please check which adapter you actually use and re-open the issue in their repo directly instead. The two adapters I am aware of are:

- https://github.com/iobroker-community-adapters/ioBroker.myvbus
- https://github.com/Grizzelbee/ioBroker.resol

Perhaps one of those is the adapter you are using :)

Best regards,
Daniel
