### ISSUE TITLE
Node-RED integration running in Docker

### ISSUE THREAD

**Issue by sporkbyspork** [danielwippermann/resol-vbus#89]
What would be the most reasonable way to control my Deltasol BX/KM2 via Node-RED?
I run Node-RED in Docker on an Intel x64-based Synology NAS.
I successfully managed to change values on the controller via the provided command line tools but am at my wits' end here.
Any hints are welcome.
Maybe also dockerizing resol-vbus and controlling via MQTT?

**Comment by danielwippermann** [comment]
Hi @sporkbyspork !

I'm sorry to say that I don't feel experienced enough to judge what the most reasonable approach would be in conjunction with Node-RED. Perhaps if you ask in the Google Group you can reach a broader audience to answer that question.

But a MQTT bridge has been on my todo list for quiet some time now.

The KM2 has such a bridge integrated in its firmware. It already performs the following tasks:

- it publishes every VBus data primitives (packets, datagrams or telegrams) that it receives from the VBus
- it allows to send VBus data primitives that you constructed yourself
- it allows to subscribe to certain controller menu values which will be actively read out either once or repeatedly in regular intervals
- it allows to change controller menu values

But this internal MQTT bridge in the KM2 is only used for intra-device communication and not designed for public use since its API is unstable and undocumented! So having a public clean-room implementation of such a bridge is something I'd really like to work on in the future.

But perhaps your inquiry will yield a ready-to-use solution from someone else that has not been on my radar!

I'll keep this issue open for some time to encourage discussion, but will close it as soon as it seem to go stale.

Best regards,
Daniel

**Comment by sporkbyspork** [comment]
Hi @danielwippermann ,

thank you for your response. Very interesting to hear that the KM2 runs MQTT internally!

Maybe a bit of overkill, but I might be able to run resol-vbus in a small VM which reacts to MQTT commands.

Any other idea on how to easily trigger configuration changes via some home automation system?
(I'd like to quickly switch between the upper and lower solar register and can already do that by calling the customizer)

Best regards!

**Comment by danielwippermann** [comment]
Hi @sporkbyspork!

Yeah, a full VM sounds like overkill. But can you add custom Docker containers to your Synology NAS or does it need to be hosted on Docker Hub? Because you could of course just build a custom Docker container that includes a VBus-to-home-automation bridge without the need for a full-blown VM.

As a potential starting point I have an example here that has been lying around in my local examples folder. It basically provides a HTTP server exposing two endpoints:

1) `GET http://<URL/>vbus/<ADDRESS>/value/<VALUEINDEX>/read` for reading a controller's value
2) `POST http://<URL>/vbus/<ADDRESS>/value/<VALUEINDEX>/write/<VALUE>` for writing a controller's value

`<ADDRESS>` must be replaced by your controller's address (e.g. `0x7341`) and the value index must be adapted as well (you probably already know that from the customizer CLI tool usage).

You could then tell your home automatiion system to access those HTTP endpoints.

Extending that example to support MQTT in addition to HTTP should be quite simple.

Best regards,
Daniel

**Comment by danielwippermann** [comment]
Hi @sporkbyspork !

for a different project I experimented with crosscompiling the Rust version of the VBus code for the KM2 which worked out quiet nicely (only drawbacks I found were that the executables are quiet large and some libraries so not support the KM2's MIPS processor architecture).

After that other project was done I hacked together a MQTT connected customizer proof-of-concept just to see whether all needed libraries would work on the KM2. And they did!

That proof-of-concept is not done yet:

- [x] Receive VBus data from the KM2's backend over the MQTT topic "vbus/1/rx/raw"
- [x] Transmit VBus data to the KM2's backend over the MQTT topic "vbus/1/tx/raw"
- [x] Add a queue for outstanding customizer requests
- [x] Receive requests over the MQTT topic "customizer/request"
- [ ] Parse and queue customizer requests (not done yet, need to specify format)
- [x] Wait for VBus bus offering when queue is not empty
- [ ] Read a value by its index from the controller (partially done, index is hardcoded at the moment)
- [ ] Write a value by its index to the controller
- [ ] Release the VBus once the queue is empty again
- [x] Publish replies for completed requests over the MQTT topic "customizer/reply"
- [ ] Build init scripts to start the customizer on boot

It looks promising and could be a light-weight approach without the need for a VM or Docker container. But since Rust targets other architectures as well that approach could be used in a x86-64 Docker container as well.

Best regards,
Daniel
